playing around

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -9,28 +9,24 @@ jobs:
     strategy:
       fail-fast: false
 
-      matrix:
-        target:
-          - x86_64-unknown-linux-gnu
-          - aarch64-unknown-linux-gnu
+      # matrix:
+      #   target:
+      #     - x86_64-unknown-linux-gnu
+      #     - aarch64-unknown-linux-gnu
 
     steps:
       - uses: actions/checkout@v3
-      - uses: actions-rs/toolchain@v1
+      - name: Install Nix
+        uses: DeterminateSystems/nix-installer-action@main
+      - uses: cachix/toolchain@v1
         with:
-          toolchain: nightly
-          profile: minimal
-          override: true
-      - uses: actions-rs/cargo@v1
-        with:
-          command: test
-          use-cross: true
-          args: --target ${{ matrix.target }}
-      - uses: actions-rs/cargo@v1
-        with:
-          command: run
-          use-cross: true
-          args: --package io-uring-test --features io-uring-test/ci --target ${{ matrix.target }}
+          name: snowytrees
+          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
+      - name: Build tests
+        run: nix build .#io-uring-test-ci
+      - name: Run tests
+        run:
+          ./result/bin/io-uring-test
 
   check-bench:
     runs-on: ubuntu-latest
@@ -45,11 +41,12 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - uses: actions-rs/toolchain@v1
+      - name: Install Nix
+        uses: DeterminateSystems/nix-installer-action@main
+      - uses: cachix/toolchain@v1
         with:
-          toolchain: nightly
-          profile: minimal
-          components: clippy
-          override: true
+          name: snowytrees
+          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
       - uses: actions-rs/clippy-check@v1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
@@ -61,44 +58,47 @@ jobs:
     strategy:
       fail-fast: false
 
-      matrix:
-        toolchain:
-          - nightly
-          - "1.48"
-        target:
-          - x86_64-unknown-linux-gnu
-          - x86_64-unknown-linux-musl
-          - i686-unknown-linux-gnu
-          - aarch64-unknown-linux-gnu
-          - mips64-unknown-linux-gnuabi64
+    #   matrix:
+    #     target:
+    #       - x86_64-unknown-linux-gnu
+    #       - x86_64-unknown-linux-musl
+    #       - i686-unknown-linux-gnu
+    #       - aarch64-unknown-linux-gnu
+    #       - mips64-unknown-linux-gnuabi64
 
     steps:
       - uses: actions/checkout@v3
       - uses: actions-rs/toolchain@v1
+      - name: Install Nix
+        uses: DeterminateSystems/nix-installer-action@main
+      - uses: cachix/toolchain@v1
         with:
-            toolchain: ${{ matrix.toolchain }}
-            target: ${{ matrix.target }}
-            components: clippy
-            override: true
+          name: snowytrees
+          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
+      - name: Enter dev shell
+        run: nix develop .#
       - uses: actions-rs/clippy-check@v1
-        with:
+        with: 
           token: ${{ secrets.GITHUB_TOKEN }}
-          args: --target ${{ matrix.target }}
-
 
   fmt:
     name: fmt
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: Install Rust
-        run: rustup update stable
-      - name: Install rustfmt
-        run: rustup component add rustfmt
+      - uses: actions-rs/toolchain@v1
+      - name: Install Nix
+        uses: DeterminateSystems/nix-installer-action@main
+      - uses: cachix/toolchain@v1
+        with:
+          name: snowytrees
+          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
+      - name: Enter dev shell
+        run: nix develop .#
 
       - name: "rustfmt --check"
         run: |
-          if ! rustfmt --check --edition 2018 $(find . -name '*.rs' -print); then
-            printf "Please run \`rustfmt --edition 2018 \$(find . -name '*.rs' -print)\` to fix rustfmt errors.\n" >&2
+          if ! rustfmt --edition 2021 --check $(find . -name '*.rs' -print); then
+            printf "Please run \`rustfmt --edition 2021 \$(find . -name '*.rs' -print)\` to fix rustfmt errors.\n" >&2
             exit 1
           fi
